[deps]
CDDLib = "3391f64e-dcde-5f30-b752-e11513730f60"
CSDP = "0a46da34-8e4b-519e-b418-48813639ff34"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
DAQP = "c47d62df-3981-49c8-9651-128b1cd08617"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
HybridSystems = "2207ec0c-686c-5054-b4d2-543502888820"
ImplicitPlots = "55ecb840-b828-11e9-1645-43f4a9f9ace7"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
MathematicalSystems = "d14a8603-c872-5ed3-9ece-53e0e82e39da"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PATHSolver = "f5f7c340-0bb3-5c69-969a-41884d311d1b"
Pajarito = "2f354839-79df-5901-9f0a-cdb2aac6fe30"
ParametricDAQP = "19f72acb-e2a9-45c8-96b9-4d5487c8db2e"
ParametricOptInterface = "0ce4ce61-57bf-432b-a095-efac525d185e"
Pavito = "cd433a01-47d1-575d-afb7-6db927ee8d8f"
PiecewiseAffineApprox = "029c5f1c-0dc4-4551-8b87-a10b73fe3713"
PiecewiseLinearOpt = "0f51c51e-adfa-5141-8a04-d40246b8977c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
ReachabilityAnalysis = "1e97bd63-91d1-579d-8e8d-501d2b57c93f"
ReachabilityModels = "20aa409e-046b-4a69-a2fd-3a10e4fb9b33"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"
SumOfSquares = "4b9e565b-77fc-50a5-a571-1244f986bda1"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TypedPolynomials = "afbbf031-7a57-5f58-a1b9-b774a0fad08d"

[sources]
ReachabilityModels = {rev = "master", url = "https://github.com/JuliaReach/ReachabilityModels.jl"}
